version: "2.4"

networks:

  web_net:
    driver: bridge

  backend_net:
    driver: bridge

services:

  web:
    build: src/web
    image: web
    environment:
      - PORT=80
      - API=http://api:8080
    networks:
      web_net:
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    build: src/api
    image: api
    environment:
      - PORT=8080
      - DATABASE_NAME=database
    networks:
      - web_net
      - backend_net
    ports:
      - "8080"
    depends_on:
      - database

  database:
    image: mongo:5.0
    networks:
      - backend_net
    ports:
      - "27017"
