apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: voting-demo
build:
  artifacts:
    - image: gcr.io/voting-app/frontend
      context: src/frontend
      docker:
        dockerfile: Dockerfile
    - image: gcr.io/voting-app/api
      context: src/api
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
  googleCloudBuild: {}
deploy:
  kubectl:
    manifests:
      - kubernetes/database.yaml
      - kubernetes/api.yaml
      - kubernetes/frontend-external.yaml
      - kubernetes/frontend.yaml
