version: '2.4'

services:

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"

  postgres:
    image: postgres:14.0
    ports:
      - "5432:5432"
    environment:
      # Read password from shell environment
      - PGPASSWORD
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=votes
      - PGUSER=postgres
      # For psql
      - PGPASSWORD
