version: '2.4'

networks:
  test_net:
    driver: bridge

services:

  sut:
    build: .
    command: npm test
    environment:
      # Read password from shell environment
      - PGPASSWORD
    networks:
      - test_net
    depends_on:
      - mongo
      - postgres

  mongo:
    image: mongo:5.0
    networks:
      - test_net

  postgres:
    image: postgres:14.0
    ports:
      - "5432:5432"
    environment:
      # Read password from shell environment
      - POSTGRES_PASSWORD
      - PGPASSWORD
      - PGUSER=postgres
      - PGDATABASE=votes
    networks:
      - test_net
